services:
  db:
    image: postgres:18-alpine # Download the Postgres image
    environment: # Pull from env file
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck: # pings Postgres every 5s - other services wait for this to pass before starting
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend # Find the Dockerfile on backend folder
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE:-disable}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend # Find the Dockerfile on frontend folder
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
